### PR TITLE
ENG-3151 - Refactored Liquibase initialization using XML

### PR DESCRIPTION
**Pull request by zonia3000**
Summary:

* Logic contained in SQL initialization files has been translated into Liquibase XML syntax
  * `00000000000001_dataPort_production.sql` -> `00000000000001_dataPort_production.xml`
* All CLOB content has been moved to external files

Should be tested together with [related engine PR](https://github.com/entando/entando-engine/pull/220).

### CODE REVIEW

**Comment by zonia3000** [comment]
please retest this

**Comment by cecchisandrone** [comment]
Are we missing `entando-engine` updated version reference in `pom.xml`?

**Comment by zonia3000** [comment]
> Are we missing `entando-engine` updated version reference in `pom.xml`?

Done

**Review by cecchisandrone — APPROVED** [review]

**Comment by zonia3000** [comment]
It looks that after fetching new changes it was necessary to update the log4j version too.
Startup failed with error `java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/util/SetUtils`

**Pull request merged**
